### ISSUE TITLE
One of the Switcheroo message doesn't parse right

### ISSUE THREAD

**Issue by JukeDragh** [IdleLands/Custom-Assets#45]
https://github.com/IdleLands/Custom-Assets/blob/master/events/flipStat.txt
I got Line 8 the other day and it didn't remove %stat

**Comment by KennethShen** [comment]
Switcheroo uses [%flipStat](https://github.com/IdleLands/IdleLands/blob/42928e478459aca81c67ba3e5c03c90af0372946/src/plugins/events/events/Switcheroo.js#L18)
