### ISSUE TITLE
Red Tearstone Ring's base item score is negative

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/Custom-Assets#46]
https://github.com/IdleLands/Custom-Assets/blob/master/items/finger.txt#L49
Based on[ current equipment score calculations](https://github.com/IdleLands/IdleLands/blob/fd5089cac88872bd10fceaa39b7f0a8a5341e4fa/src/core/base/equipment.js)
1000 str 1000 dex 1000 int -20000 hp 
`1000 * 1.5 + 1000 + 1000 * 2 - 20000 * 0.5 = -5500`

This can result in items with negative item score which have unbounded growth.

**Comment by seiyria** [comment]
fixed, thanks
